<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ajax_example"
 *
 * Auto generated by Extension Builder 19-02-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Ajax Example Extension',
	'description' => 'Just an example for a Blog Post',
	'category' => 'Example Extensions',
	'author' => 'Helmut Hummel',
	'author_email' => '',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'php' => '5.5.0-7.0.999',
			'typo3' => '6.0.0-6.3.999',
			'typoscript_rendering' => '*',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'news' => '*'
		),
	),
);

?>